### ISSUE TITLE
Schemas/Models title change size when opened

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#100]
When we open/close the title of schemas/models it changes its size
probably in css class `.swagger-ui .model-title` we need to change `font` to `font-size`
https://user-images.githubusercontent.com/16152347/180438560-246ac8bf-4c1d-441b-b1a8-5e6bb3ecbd21.mov

**Comment by pk-hotovo** [comment]
PR: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/47
