### ISSUE TITLE
Schemas/Models arrow wrong color

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#101]
The arrow in Schemas/Models should be in color of `--model-collapse-icon-color` instead of black

![Screenshot 2022-07-22 at 14 25 41](https://user-images.githubusercontent.com/16152347/180438935-9a6d759c-40d5-447e-b062-1bf1880d70b1.png)

**Comment by pk-hotovo** [comment]
fixed: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/46
