### ISSUE TITLE
Error `Failed prop type: invariant is not defined`

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#102]
We have an error in console
![Screenshot 2022-07-22 at 14 27 11](https://user-images.githubusercontent.com/16152347/180439114-3fdee196-57a9-407b-becc-33b080200dd8.png)
 
please investigate and fix it if possible.

**Comment by JulianEstefanHotovo** [comment]
I don't see the same Error in my console and we also don't have any reference to invariant in our codebase

**Comment by tomaszwylezek** [comment]
lets leave it then
