### ISSUE TITLE
Execute/clear buttons size

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#103]
Please adjust the size of execute/clear buttons size to be same as in portal provided
![Screenshot 2022-07-22 at 14 09 11](https://user-images.githubusercontent.com/16152347/180439313-d8ab6eec-b87c-4843-a747-f560b646fbe9.png)

**Comment by pk-hotovo** [comment]
PR: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/49
