### ISSUE TITLE
Button styles in v4 don't match the look and feel of previous version

### ISSUE THREAD

**Issue by tkajtoch** [Kong/swagger-ui-kong-theme#80]
Please update the styles of buttons used in `next/4.x`. For more details about focus and active states, you can take a look at https://beta.kongponents.konghq.com/components/button.html

**Current result:**
<img width="184" alt="Screenshot 2022-07-12 at 10 22 21" src="https://user-images.githubusercontent.com/1282498/178446165-7096d9a2-436b-437f-ac38-7f607f6a83d0.png">
<img width="135" alt="Screenshot 2022-07-12 at 10 22 27" src="https://user-images.githubusercontent.com/1282498/178446178-0e254480-ff5f-419c-9dfa-0eec33d75ada.png">

**Expected result:**
<img width="329" alt="Screenshot 2022-07-12 at 10 21 42" src="https://user-images.githubusercontent.com/1282498/178446221-c65442da-0f6e-447b-958e-2d0239e950ec.png">

**Comment by pk-hotovo** [comment]
Assigned to pk-hotovo

**Comment by pk-hotovo** [comment]
Assigned to pk-hotovo

**Comment by pk-hotovo** [comment]
created PR

**Comment by tomaszwylezek** [comment]
closing in favor of #91
