### ISSUE TITLE
Specification Header doesn't match the expected style

### ISSUE THREAD

**Issue by tkajtoch** [Kong/swagger-ui-kong-theme#81]
Please modify the Spec Header component to fix the styles and include the Scheme and Version selects, Authorize button and View Raw button.

**Current result**
<img width="1533" alt="Screenshot 2022-07-12 at 10 31 46" src="https://user-images.githubusercontent.com/1282498/178446827-8d7e72aa-e70e-4afa-b2e6-e66bc176c3e0.png">

**Expected result**
<img width="1100" alt="Screenshot 2022-07-12 at 10 30 53" src="https://user-images.githubusercontent.com/1282498/178446858-5211ab16-4118-4df4-8b20-e2edd5f0d5fa.png">

**Comment by pk-hotovo** [comment]
assinged to pk-hotovo

**Comment by pk-hotovo** [comment]
assigned to pk-hotovo
