### ISSUE TITLE
Paths and Tag Groups don't match the expected styles

### ISSUE THREAD

**Issue by tkajtoch** [Kong/swagger-ui-kong-theme#82]
Please make the Path and Tag Group components styles configurable using CSS variables.

**Current result**
<img width="1517" alt="Screenshot 2022-07-12 at 10 43 47" src="https://user-images.githubusercontent.com/1282498/178449250-557d94e3-2228-4cf5-93be-f55066dc6f9f.png">

**Expected result**
<img width="1116" alt="Screenshot 2022-07-12 at 10 45 08" src="https://user-images.githubusercontent.com/1282498/178449388-3bdafbf5-12ad-44c1-92d4-8b1385d15dab.png">

**Comment by pk-hotovo** [comment]
created PR: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/17
