### ISSUE TITLE
Sidebar doesn't match the expected styles

### ISSUE THREAD

**Issue by tkajtoch** [Kong/swagger-ui-kong-theme#84]
**Current result**
<img width="268" alt="Screenshot 2022-07-12 at 10 51 20" src="https://user-images.githubusercontent.com/1282498/178450721-dc3bb0bf-a89e-4548-b702-9e8d1508baaf.png">

**Expected result**
<img width="263" alt="Screenshot 2022-07-12 at 10 51 33" src="https://user-images.githubusercontent.com/1282498/178450744-4a32cd7e-8e8b-46cf-a1c5-3f72ca27bfec.png">

**Comment by pk-hotovo** [comment]
![image](https://user-images.githubusercontent.com/106535508/178478188-966b9943-2c5e-4ff4-a261-31e338ce2e44.png)
This is current state for dev branch. Are you sure you have code up to current state?

**Comment by pk-hotovo** [comment]
fix implemented
