### ISSUE TITLE
Sidebar style and accessibility improvements

### ISSUE THREAD

**Issue by tkajtoch** [Kong/swagger-ui-kong-theme#86]
**Acceptance Criteria**

- Sidebar should **not** have `border-right`
- Sidebar container (`.sidebar-menu`) should have the padding set to `2rem 1.5rem`
- Sidebar mobile view should open from the left side, not the right side
- Sidebar mobile (open state) width should be configurable via `--sidebar-width-mobile` (fallback to `300px`)
- Sidebar mobile open/close sidebar should be a hamburger icon instead of `Open / Close sidebar` text
- Sidebar width should be configurable via `--sidebar-width` (fallback to `300px`)
- Filter: Input border, background, color and font properties should be configurable:
    - `--sidebar-filter-font-size` (fallback to `1rem`)
    - `--sidebar-filter-font-weight` (fallback to `400`)
    - `--sidebar-filter-color` (fallback to `#333`)
    - `--sidebar-filter-background` (fallback to `transparent`)
    - `--sidebar-filter-border-color` (fallback to `#E6E6E6`)
    - `--sidebar-filter-border-radius` (fallback to `0.25rem`)
- Path (list item) should have a configurable color and font properties:
    - `--sidebar-path-color` (fallback to `#333`)
    - `--sidebar-path-font-size` (fallback to `0.875rem`)
    - `--sidebar-path-font-weight` (fallback to `400`)
- Tag (group) should have a configurable color and font properties:
    - `--sidebar-tag-color` (fallback to `#333`)
    - `--sidebar-tag-font-size` (fallback to `1rem`)
    - `--sidebar-tag-font-weight` (fallback to `600`)

**Comment by tomaszwylezek** [comment]
Looks good to me.
