### ISSUE TITLE
Buttons adjustment

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#91]
Followup on #80 

Overall the design of the buttons has been adjusted, but there is a minor change required.

**Current result**
![Screenshot 2022-07-18 at 14 57 58](https://user-images.githubusercontent.com/16152347/179516355-1a30eff1-f37d-4b8c-843f-c345f6f9b8c1.png)

**Expected result**
![Screenshot 2022-07-18 at 14 58 03](https://user-images.githubusercontent.com/16152347/179516390-f423cd4e-9705-45b8-acb4-1e317fdab42e.png)

**Current result**
![Screenshot 2022-07-18 at 15 02 51](https://user-images.githubusercontent.com/16152347/179517113-874a770f-21f9-4ec2-ace6-19edbcc7e2fc.png)

**Expected result**
![Screenshot 2022-07-18 at 15 02 53](https://user-images.githubusercontent.com/16152347/179517134-67b703cf-657e-40c1-8cd2-7e8eb4b9ae4c.png)

**Current result**

![Screenshot 2022-07-18 at 16 04 46](https://user-images.githubusercontent.com/16152347/179529336-0408a13b-8c3a-42c9-952b-e8d299cd79e3.png)

**Expected result**

![Screenshot 2022-07-18 at 16 04 48](https://user-images.githubusercontent.com/16152347/179529372-da6af738-f819-4a9c-ae30-3fbb5a18f2ed.png)

Please update the color of "View Raw" button.
Please adjust the spacing between "View Raw" and " Authorize" Button
Please adjust the position of buttons in modal
Please adjust size & colors of execute/clear buttons

**Comment by pk-hotovo** [comment]
PR: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/33

**Comment by tomaszwylezek** [comment]
![Screenshot 2022-07-19 at 16 09 37](https://user-images.githubusercontent.com/16152347/179771619-21e55a3f-0b11-47a8-b8eb-a91ffedc4916.png)

We should adjust the spacing on the left side
I will proide a value for a border color to make sure it suits the requirements

**Comment by tomaszwylezek** [comment]
Border color of button should be `--section_colors-stroke`

**Comment by tomaszwylezek** [comment]
resolved in https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/45
