### ISSUE TITLE
Models and Schemas panel style adjustments

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#94]
Followup on #85 

One hasn't been done in the previous one

- Model / Schema arrow right icon should be centered vertically, and its fill color should be configurable via --model-collapse-icon-color (fallback to #07A88D) CSS variable
- Header: there should be a border-bottom set on the whole heading and it should adjust color on hover

**Current solution**
![Screenshot 2022-07-18 at 16 22 21](https://user-images.githubusercontent.com/16152347/179532728-78c7be9c-71fe-4656-b958-66c535b5f809.png)

**Expected solution**
![Screenshot 2022-07-18 at 16 22 38](https://user-images.githubusercontent.com/16152347/179532757-678b186f-7c43-4678-962f-5f4c2c895ab6.png)

**Comment by pk-hotovo** [comment]
PR: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/36

**Comment by tomaszwylezek** [comment]
Everything looks fine except for a border-bottom - needs a review later on

**Comment by tomaszwylezek** [comment]
Border-bottom is missing on feature feature/hotovo-kong-dev branch

**Comment by tomaszwylezek** [comment]
Checked, its done
