### ISSUE TITLE
Title adjustments in spec detail section

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#95]
We should adjust the size & color of the title in the spec detail section

- color should be customizable via css-variable
- size should be `--type-xl`
- make sure the "badges" are also aligned with text

**Current solution**
![Screenshot 2022-07-19 at 16 30 27](https://user-images.githubusercontent.com/16152347/179776154-5a4dcf5a-192f-4fd2-9258-850243d88c7c.png)

**Excepted solution**
![Screenshot 2022-07-19 at 16 30 31](https://user-images.githubusercontent.com/16152347/179776187-5cc75e8b-e52a-4a3d-a9e9-47ce8360e869.png)

**Comment by pk-hotovo** [comment]
addressed: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/39

**Comment by pk-hotovo** [comment]
PR merged
