### ISSUE TITLE
Markdown render section adjustments

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#96]
Section, where the Markdown is rendered, should be wrapped with a box with proper padding

- border color should match `--section_colors-stroke` fallback to `rgba(0, 0, 0, 0.1)`
- border-radius - 3px
- margin top/bottom - `--spacing-xl`
- padding should match -  `--spacing-xl`

**Current solution**
![Screenshot 2022-07-19 at 16 39 18](https://user-images.githubusercontent.com/16152347/179778295-fbdfb201-d91b-4fc5-8b6a-8ffea9ce4470.png)

**Expected solution**
![Screenshot 2022-07-19 at 16 39 25](https://user-images.githubusercontent.com/16152347/179778356-f45052b5-a8e4-464f-93b0-f7e85081b01e.png)

**Comment by pk-hotovo** [comment]
addressed in : https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/40

**Comment by pk-hotovo** [comment]
PR merged
