### ISSUE TITLE
Resoruces title adjustments

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#97]
- Everything should be aligned to left
- There shouldn't be a border-bottom on these items
- There shouldn't be change of background color on hover
- Title should be color `--headings-color`

**Current solution**
![Screenshot 2022-07-19 at 16 46 22](https://user-images.githubusercontent.com/16152347/179779884-ac08db35-5dbe-4160-bad9-a2f6fa39467e.png)

**Excepted solution**
![Screenshot 2022-07-19 at 16 46 11](https://user-images.githubusercontent.com/16152347/179779923-8f8a4560-ba95-46f6-ac18-e4a894ae013c.png)

**Comment by pk-hotovo** [comment]
addressed in : https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/38

**Comment by tomaszwylezek** [comment]
The info box border is missing

**Comment by tomaszwylezek** [comment]
looks good, closing
