### ISSUE TITLE
Servers & Schemes adjustments

### ISSUE THREAD

**Issue by tomaszwylezek** [Kong/swagger-ui-kong-theme#98]
- Border color should be `--section_colors-stroke`
- Line at the bottom should be also color `--section_colors-stroke` instead of `--white-rgb-250`
- Text Servers/Schemes should be aligned with button (centred)

**Current solution**
![Screenshot 2022-07-19 at 16 53 30](https://user-images.githubusercontent.com/16152347/179781527-6de55938-fed1-463d-8d02-86bcc70fc209.png)

**Expected solution**
![Screenshot 2022-07-19 at 16 53 33](https://user-images.githubusercontent.com/16152347/179781583-0f56ffac-9e78-41ac-9fe5-0331b4a4273b.png)

**Comment by pk-hotovo** [comment]
addressed in : https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/40

**Comment by pk-hotovo** [comment]
addressed in: https://github.com/pk-hotovo/swagger-ui-kong-theme/pull/41
